services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: media-atlas-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - media-atlas

    db:
        image: postgres:15
        container_name: media-atlas-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:${DB_PORT}"
        volumes:
            - media-atlas:/var/lib/postgresql/data
        networks:
            - media-atlas

    nginx:
        image: nginx:alpine
        container_name: media-atlas-nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - media-atlas

volumes:
    media-atlas:

networks:
    media-atlas: